services:
  db:
    container_name: postgres-ems
    image: postgres:latest
    environment:
      POSTGRES_DB: eventsystem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  keycloak:
    container_name: keycloak-ems
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: eventsystem
      DB_USER: root
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak:/opt/keycloak/data
    ports:
      - "9090:8080"
    depends_on:
      - db
    networks:
      - db
    restart: unless-stopped
    command:
      - "start-dev"
networks:
  db:
    driver: bridge
volumes:
  db:
  keycloak: